apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pv-claim # name of PVC essential for identifying the storage data
    labels:
        app: postgres
        tier: database
spec:
    accessModes:
        - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
    resources:
        requests:
            storage: 1Gi    #This will tell kubernetes about the amount of space we are trying to claim.
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres  # Sets Deployment name
    labels:
        app: postgres
        tier: database
spec:
    selector:
        matchLabels:
            app: postgres
            tier: database
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: postgres
                tier: database
        spec:
            containers:
                -   name: postgres
                    image: postgres:latest # Sets Image
                    env:
                        -   name: POSTGRES_PASSWORD
                            value: postgres

                        -   name: POSTGRES_DATABASE # Setting Database Name from a 'ConfigMap'
                            value: postgres
                    ports:
                        -   containerPort: 5432  # Exposes container port
                            name: postgres

                    volumeMounts:
                        -   mountPath: /var/lib/postgresql/data
                            name: postgredb
            volumes:
                -   name: postgredb
                    persistentVolumeClaim:
                        claimName: postgres-pv-claim

---
# Define a 'Service' To Expose postgres to Other Services
apiVersion: v1
kind: Service
metadata:
    name: postgres  # DNS name
    labels:
        app: postgres
        tier: database
spec:
    ports:
        -   port: 5432
            targetPort: 5432
    selector: # postgres Pod Should contain same labels
        app: postgres
        tier: database
    clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant