app:
    jwtExpirationMs: ${JWT_EXPIRATION:7200000}
    jwtSecret: ${JWT_SECRET:uK5Qv3OVXZRAjYVnjb8jFjeG0D2NCjrtjpwKy86LlkCbPUdR}
server:
    port: ${PORT:8080}
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${POSTGRESQL_PASSWORD:123456789@A}
        url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/university_management
        username: ${POSTGRESQL_USERNAME:postgres}
    devtools:
        restart:
            enabled: true
    flyway:
        baseline-on-migrate: true
        enabled: true
        locations: classpath:db/migration
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    cache:
        type: redis
    data:
        redis:
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}

swagger:
    title: SpringBoot API
    description: SpringBoot sample application
    version: v0.0.1
    license: springdoc-openapi
    licenseUrl: https://springdoc.org