app:
    jwtExpirationMs: ${JWT_EXPIRATION:7200000}
    jwtSecret: ${JWT_SECRET:uK5Qv3OVXZRAjYVnjb8jFjeG0D2NCjrtjpwKy86LlkCbPUdR}
server:
    port: ${PORT:8080}
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${POSTGRESQL_PASSWORD:123456789@A}
        url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/university_management
        username: ${POSTGRESQL_USERNAME:postgres}
    devtools:
        restart:
            enabled: true
    flyway:
        baseline-on-migrate: true
        enabled: true
        locations: classpath:db/migration
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true

azure:
    storage:
        connection-string: DefaultEndpointsProtocol=https;AccountName=cs11003200310f45d55;AccountKey=8vZWBEkg/KsIYu8W4LargzizPxZLSTqOoAPCRC4zEKP3PjEiT6hHvRIwg4soInni7h9knLXpnJDR+ASt3YvURA==;EndpointSuffix=core.windows.net
        container-name: images-storage

swagger:
    title: SpringBoot API
    description: SpringBoot sample application
    version: v0.0.1
    license: springdoc-openapi
    licenseUrl: https://springdoc.org
logging:
    file:
        name: F:/logs/elk-stack.log
    level:
        root: INFO



